[font.bold]
family = "Fira Code"
style = "bold"
[font.italic]
family = "Fira Code"
style = "italic"
[font.normal]
family = "Fira Code"
style = "normal"
[font.bold_italic]
family = "Fira Code"
style = "bold_italic"



